name: Continuous Integration

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install Dependencies
      run: npm install

    - name: Lint
      run: npm run lint

    - name: Run Unit Tests
      run: npm run test:unit

    - name: Build
      run: npm run build

    - name: Preview Build
      run: npm run preview &
      
    - name: Run E2E Tests
      run: npm run test:e2e
